"""
Report Generator
================
Creates professional audit reports of all scan activities
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List
from config.settings import REPORT_PATH


class ReportGenerator:
    """مولد تقارير التدقيق الأمني"""

    def __init__(self):
        self.events = []
        self.start_time = datetime.now()

    def log_event(self, event_type: str, details: str):
        """تسجيل حدث في السجل"""
        self.events.append({
            "timestamp": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            "type": event_type,
            "details": details,
        })

    def log_threat(self, threat: Dict):
        """تسجيل تهديد مكتشف"""
        self.log_event(
            "THREAT_DETECTED",
            f"[{threat.get('severity')}] {threat.get('type')} — {threat.get('source')}: {threat.get('details')}"
        )

    def log_action(self, command: str, approved: bool, result: Dict = None):
        """تسجيل إجراء تم اتخاذه"""
        status = "APPROVED & EXECUTED" if approved else "REJECTED BY USER"
        details = f"Command: {command} | Status: {status}"
        if result:
            details += f" | Success: {result.get('success', False)}"
        self.log_event("ACTION", details)

    def generate(self, system_info: Dict, analysis_result: Dict) -> str:
        """توليد التقرير النهائي"""
        end_time = datetime.now()
        duration = (end_time - self.start_time).total_seconds()

        lines = []
        lines.append("=" * 70)
        lines.append("           C.O.A — Council of Agents")
        lines.append("           Security Audit Report")
        lines.append("=" * 70)
        lines.append("")

        # === معلومات الجلسة ===
        lines.append("📋 SESSION INFO")
        lines.append("-" * 70)
        lines.append(f"  Scan Start:    {self.start_time.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"  Scan End:      {end_time.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"  Duration:      {duration:.2f} seconds")
        lines.append(f"  Hostname:      {system_info.get('hostname', 'N/A')}")
        lines.append("")

        # === معلومات النظام ===
        lines.append("💻 SYSTEM INFORMATION")
        lines.append("-" * 70)
        for key, value in system_info.items():
            if key != "scan_time":
                lines.append(f"  {key:20s}: {value}")
        lines.append("")

        # === ملخص التهديدات ===
        lines.append("🚨 THREAT SUMMARY")
        lines.append("-" * 70)
        lines.append(f"  Total Threats Detected: {analysis_result.get('total_threats', 0)}")
        lines.append(f"    • CRITICAL: {analysis_result.get('critical', 0)}")
        lines.append(f"    • HIGH:     {analysis_result.get('high', 0)}")
        lines.append(f"    • MEDIUM:   {analysis_result.get('medium', 0)}")
        lines.append(f"    • LOW:      {analysis_result.get('low', 0)}")
        lines.append("")

        # === التهديدات التفصيلية ===
        threats = analysis_result.get('threats', [])
        if threats:
            lines.append("🔍 DETAILED THREATS")
            lines.append("-" * 70)
            for i, threat in enumerate(threats, 1):
                lines.append(f"  [{i}] Severity: {threat.get('severity')}")
                lines.append(f"      Type:     {threat.get('type')}")
                lines.append(f"      Source:   {threat.get('source')}")
                lines.append(f"      Details:  {threat.get('details')}")
                lines.append(f"      Action:   {threat.get('recommended_action')}")
                lines.append("")

        # === سجل الأحداث ===
        lines.append("📜 EVENT LOG")
        lines.append("-" * 70)
        for event in self.events:
            lines.append(f"  [{event['timestamp']}] {event['type']}")
            lines.append(f"      {event['details']}")
            lines.append("")

        # === التذييل ===
        lines.append("=" * 70)
        lines.append("  Generated by C.O.A — All data remains local & private 🔒")
        lines.append("=" * 70)

        report_content = "\n".join(lines)

        # حفظ الملف
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(REPORT_PATH, "w", encoding="utf-8") as f:
            f.write(report_content)

        return str(REPORT_PATH)
